name: CI/CD with Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t image-for-lab ./lab_3

    - name: Run Docker Container
      run: docker run --name container-for-lab image-for-lab
      
    - name: Copy File From Container
      run: sudo docker cp container-for-lab:/build_output.txt ${{ github.workspace }}

    - name: Push File To Repo
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add build_output.txt
        git commit -m "Result of building image has been pushed on repo"
        git push origin main
